FROM ubuntu:latest

RUN apt-get update
RUN apt-get install --no-install-recommends --no-install-suggests -y curl

ENV SITE_URL http://google.com/

WORKDIR /data

COPY tmp/some_file.txt /data

VOLUME /data
COPY tmp/new_file.txt /data

COPY ./ /opt/project

CMD sh -c "curl -L $SITE_URL > /data/results"
