pipeline {
  agent {
      any {
      }
  }
  parameters {
    gitParameter branchFilter: 'origin/(.*)', defaultValue: 'develop', name: 'BRANCH', type: 'PT_BRANCH'
  }
  environment {
      ECR_REPO = "438378284830.dkr.ecr.eu-west-1.amazonaws.com/service/nginx"
      AWS_DEFAULT_REGION = "eu-west-1"
  }
  stages {
    stage("Docker Build") {
      steps {
        script {
         commit_hash = sh(script: 'git rev-parse --short=6 HEAD', returnStdout: true).trim()
        }
       container('docker') {
         sh "cd jenkins && docker build --network=host -t ${ECR_REPO}:${commit_hash} ."
       }
    }
    }
    stage("ECR push") {
      steps {
        container('docker') {
              script {
                def login = ecrLogin()
                sh "${login}"
                sh "docker push ${ECR_REPO}:${commit_hash}"
              }
          }
        }
      }
    stage("Clone k8s repo") {
      steps{
        dir('k8s') {}
        git branch: 'master',
            credentialsId: 'itea-deploy',
            url: 'git@github.com:Dgadavin/itea-advance-course.git'
      }
    }
    stage("Kustomize") {
      steps {
        container('kustomize') {
        dir('k8s') {}
        sh "cd nginx/kustomize/overlays/dev && /app/kustomize edit set image service/nginx=${ECR_REPO}:${commit_hash}"
        }
      }
    }
    stage("Push") {
        environment {
          HASH = "$commit_hash"
        }
        steps {
          dir('k8s') {}
          sh('''
              git config user.name 'jenkins'
              git config user.email 'maxferiartos@gmail.com'
              git add nginx/kustomize/overlays/dev/kustomization.yaml
              git commit -m "[nginx][dev] Deploy revision \$HASH"
          ''')

          sshagent(['itea-deploy']) {
              sh("""
                  #!/usr/bin/env bash
                  set +x
                  export GIT_SSH_COMMAND="ssh -oStrictHostKeyChecking=no"
                  git push origin master
               """)
          }
        }
      }
}
}
